// app/report/[id]/page.tsx
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";

type ReportPageProps = {
  params: { id: string };
};

export default async function ReportPage({ params }: ReportPageProps) {
  const { id } = params;

  const scan = await prisma.psaScan.findUnique({
    where: { urlHash: id },
  });

  if (!scan) {
    notFound();
  }

  return (
    <main
      style={{
        minHeight: "100vh",
        margin: 0,
        fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
        background: "#050505",
        color: "#f5f5f5",
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        padding: "40px 16px",
      }}
    >
      <section style={{ maxWidth: 720, width: "100%" }}>
        <div
          style={{
            display: "inline-flex",
            alignItems: "center",
            gap: 8,
            padding: "4px 10px",
            borderRadius: 999,
            background: "#111",
            border: "1px solid #333",
            fontSize: 12,
            textTransform: "uppercase",
            letterSpacing: 1,
            marginBottom: 16,
          }}
        >
          <span style={{ color: "#ffdd00" }}>PSA</span>
          <span style={{ color: "#999" }}>Certified by fajaedeAI</span>
        </div>

        <h1 style={{ fontSize: 28, marginBottom: 8 }}>
          PSA Report for this site or app
        </h1>

        <p style={{ fontSize: 14, color: "#ccc", marginBottom: 24 }}>
          Permanent PSA certificate generated by fajaedeAI.
        </p>

        <div
          style={{
            padding: 20,
            borderRadius: 16,
            background:
              "linear-gradient(135deg, rgba(255,0,0,0.18), rgba(255,221,0,0.16))",
            border: "1px solid #333",
            marginBottom: 24,
          }}
        >
          <h2 style={{ fontSize: 18, marginBottom: 8 }}>Scanned URL</h2>
          <p
            style={{
              wordBreak: "break-all",
              background: "#111",
              padding: "10px 12px",
              borderRadius: 8,
              fontSize: 13,
            }}
          >
            {scan.url}
          </p>
          {scan.pageTitle && (
            <p style={{ marginTop: 8, fontSize: 13, color: "#ddd" }}>
              Page title: {scan.pageTitle}
            </p>
          )}
          <p style={{ marginTop: 8, fontSize: 12, color: "#aaa" }}>
            First scanned on: {scan.createdAt.toISOString()}
          </p>
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
            gap: 12,
            marginBottom: 24,
          }}
        >
          <ScoreBox
            label="Privacy"
            score={scan.privacyScore}
            note={scan.privacyNote}
          />
          <ScoreBox
            label="Security"
            score={scan.securityScore}
            note={scan.securityNote}
          />
          <ScoreBox label="Age" score={scan.ageScore} note={scan.ageNote} />
        </div>
      </section>

      <footer
        style={{ marginTop: "auto", paddingTop: 40, fontSize: 12, color: "#777" }}
      >
        © {new Date().getFullYear()} fajaede.nl · PSA – Privacy Security Age ·
        fajaedeAI
      </footer>
    </main>
  );
}

function ScoreBox({
  label,
  score,
  note,
}: {
  label: string;
  score: string;
  note: string;
}) {
  return (
    <div
      style={{
        padding: 12,
        borderRadius: 12,
        background: "rgba(5,5,5,0.7)",
        border: "1px solid #333",
      }}
    >
      <div
        style={{
          fontSize: 12,
          textTransform: "uppercase",
          letterSpacing: 1,
          color: "#aaa",
          marginBottom: 4,
        }}
      >
        {label}
      </div>
      <div style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>
        {score}
      </div>
      <div style={{ fontSize: 12, color: "#ddd" }}>{note}</div>
    </div>
  );
}
